#!/usr/bin/env bash


cwd=$(dirname $0)


. $cwd/usage.bash


if [ $# -eq 0 ]; then
    usage
    exit
fi


case $1 in 

  "create")
        "$cwd/create_file.bash" $2
    ;;

  "random") 
        "$cwd/show_random_note.bash" $2
    ;;

    "select") 
        "$cwd/select.bash" $2 $3
    ;;

    "select_all") 
        "$cwd/show_notes.bash"
    ;;

    "tag") 
        "$cwd/add_tag.bash" $2
    ;;

    "edit") 
        "$cwd/edit.bash" $2
    ;;

    "clear") 
        "$cwd/clear.bash"
    ;;

    "update") 
        "$cwd/update.bash"
    ;;

    "search") 
        "$cwd/search.bash" $2 $3
    ;;

  *) 
    echo "Command not valid"
    usage 
    ;; 
esac
