#!/usr/bin/env bash


cwd=$(dirname $0)


. $cwd/usage.bash


if [ $# -eq 0 ]; then
    usage
    exit
fi


case $1 in 

  "create")
        "$cwd/create_file.bash" $2 $3
    ;;

    "c")
        "$cwd/create_file.bash" $2 $3
    ;;

    "random") 
        "$cwd/show_random_note.bash" $2
    ;;

    "r") 
        "$cwd/show_random_note.bash" $2
    ;;

    "select") 
        "$cwd/select.bash" $2 $3
    ;;

    "select_all") 
        "$cwd/show_notes.bash" $2 $3
    ;;

    "tag") 
        "$cwd/add_tag.bash" $2
    ;;

    "t") 
        "$cwd/add_tag.bash" $2
    ;;

    "edit") 
        "$cwd/edit.bash" $2
    ;;

    "e") 
        "$cwd/edit.bash" $2
    ;;

    "clear") 
        "$cwd/clear.bash"
    ;;

    "update") 
        "$cwd/update.bash"
    ;;

    "u") 
        "$cwd/update.bash"
    ;;

    "search") 
        "$cwd/search.bash" $2 $3
    ;;

    "s") 
        "$cwd/search.bash" $2 $3
    ;;

    "hide") 
        "$cwd/hide.bash" $2
    ;;

    "image") 
        "$cwd/image.bash" $2 $3 $4
    ;;

    "i") 
        "$cwd/image.bash" $2 $3 $4
    ;;

    "video")
        "$cwd/video.bash" $2 $3
    ;;

    "v")
        "$cwd/video.bash" $2 $3
    ;;

    "notification")
        "$cwd/notification.bash" $2 $3 $4 &
    ;;

    "n")
        "$cwd/notification.bash" $2 $3 $4 &
    ;;

    "open")
        "$cwd/open.bash"
    ;;

    "o")
        "$cwd/open.bash"
    ;;

    "stat")
        "$cwd/stat.bash"
    ;;

    "history")
        "$cwd/history.bash"
    ;;

    "h")
        "$cwd/history.bash"
    ;;

    "learn")
        "$cwd/learn.bash" $2
    ;;

    "l")
        "$cwd/learn.bash" $2
    ;;

    "wallpaper")
        "$cwd/wallpaper.bash" &
    ;;

    "w")
        "$cwd/wallpaper.bash" &
    ;;

    "sync")
      "$cwd/sync.bash"
    ;;

  *) 
    echo "Command not valid"
    usage 
    ;; 
esac
