#pragma once
#include <glib.h>
#include <gtk/gtk.h>
#include "app_data.h"
#include "const.h"
#include "content.h"
#include "layout.h"
#include "panel_left.h"
#include "panel_notes.h"
#include "panel_right.h"
#include "panel_tags.h"
